[package]
name = "ndraey_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.14"
reqwest = { version = "0.11.12", features = ["stream"] }
